name: Simple Actions

on: [ push ]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "say hello to :"
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: John
      - name: "Log the time"
        run: echo "${{steps.greet.outputs.time}}"






