name: PRs to develop
on:
  pull_request:
    branches: [develop]
    types: [closed]
jobs:
  merge-develop-to-uat:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge develop back to uat
        run: |
          git fetch --unshallow
          git checkout uat
          git pull
          git merge --no-ff develop -m "Auto-merge develop to uat"
          git push
